import Vue from 'vue'
import { Button, Icon, NavBar, Field, Cell, CountDown, Toast, Tabbar, TabbarItem, Image, Row, Col, Grid, GridItem, CellGroup, Dialog, Tab, Tabs, List, PullRefresh, Popup, Search, Loading, ImagePreview } from 'vant'

Vue.use(Button)
  .use(Icon)
  .use(NavBar)
  .use(Field)
  .use(Cell)
  .use(CountDown)
  .use(Toast)
  .use(Tabbar)
  .use(TabbarItem)
  .use(Image)
  .use(Row)
  .use(Col)
  .use(Grid)
  .use(GridItem)
  .use(CellGroup)
  .use(Dialog)
  .use(Tab)
  .use(Tabs)
  .use(List)
  .use(PullRefresh)
  .use(Popup)
  .use(Search)
  .use(Loading)
  .use(ImagePreview)
